import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, decimal } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Ranks table for server rank store items
 */
export const ranks = mysqlTable("ranks", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 128 }).notNull(),
  displayName: varchar("displayName", { length: 128 }).notNull(),
  price: decimal("price", { precision: 10, scale: 2 }).notNull(),
  duration: varchar("duration", { length: 64 }).default("ถาวร").notNull(),
  color: varchar("color", { length: 32 }).default("gold").notNull(),
  badge: varchar("badge", { length: 64 }).default("POPULAR").notNull(),
  description: text("description").notNull(),
  features: text("features").notNull(), // JSON string array of perks
  roleId: varchar("roleId", { length: 64 }), // Discord role ID
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Rank = typeof ranks.$inferSelect;
export type InsertRank = typeof ranks.$inferInsert;

/**
 * Orders table for purchases and slip uploads
 */
export const orders = mysqlTable("orders", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  minecraftIGN: varchar("minecraftIGN", { length: 64 }).notNull(),
  rankId: int("rankId").notNull(),
  rankName: varchar("rankName", { length: 128 }).notNull(),
  amount: decimal("amount", { precision: 10, scale: 2 }).notNull(),
  paymentMethod: varchar("paymentMethod", { length: 64 }).default("PromptPay / ออมสิน").notNull(),
  slipUrl: text("slipUrl").notNull(),
  slipKey: varchar("slipKey", { length: 255 }).notNull(),
  status: mysqlEnum("status", ["รอตรวจสอบ", "สำเร็จ", "ยกเลิก"]).default("รอตรวจสอบ").notNull(),
  adminNotes: text("adminNotes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Order = typeof orders.$inferSelect;
export type InsertOrder = typeof orders.$inferInsert;

/**
 * User wallet balance and ledger transactions
 */
export const wallets = mysqlTable("wallets", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  balance: decimal("balance", { precision: 10, scale: 2 }).default("0.00").notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Wallet = typeof wallets.$inferSelect;
export type InsertWallet = typeof wallets.$inferInsert;

export const walletTransactions = mysqlTable("wallet_transactions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  amount: decimal("amount", { precision: 10, scale: 2 }).notNull(),
  type: mysqlEnum("type", ["topup", "purchase", "refund", "admin_adjust"]).notNull(),
  description: text("description").notNull(),
  referenceKey: varchar("referenceKey", { length: 128 }).unique(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type WalletTransaction = typeof walletTransactions.$inferSelect;
export type InsertWalletTransaction = typeof walletTransactions.$inferInsert;

/**
 * Discord-to-Minecraft account links created by the verification panel.
 * One Discord user and one Minecraft UUID can only be linked once.
 */
export const discordVerifications = mysqlTable("discord_verifications", {
  id: int("id").autoincrement().primaryKey(),
  discordUserId: varchar("discordUserId", { length: 64 }).notNull().unique(),
  minecraftIGN: varchar("minecraftIGN", { length: 16 }).notNull(),
  minecraftUuid: varchar("minecraftUuid", { length: 64 }).notNull().unique(),
  bio: text("bio"),
  playStyle: varchar("playStyle", { length: 128 }),
  verifiedAt: timestamp("verifiedAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type DiscordVerification = typeof discordVerifications.$inferSelect;
export type InsertDiscordVerification = typeof discordVerifications.$inferInsert;

/**
 * Short-lived one-time codes generated by the Discord onboarding panel.
 * The Minecraft-side `/verify <code>` command redeems a row through the
 * authenticated server callback and then creates the durable account link.
 */
export const discordVerificationCodes = mysqlTable("discord_verification_codes", {
  id: int("id").autoincrement().primaryKey(),
  discordUserId: varchar("discordUserId", { length: 64 }).notNull().unique(),
  code: varchar("code", { length: 4 }).notNull(),
  expiresAt: timestamp("expiresAt").notNull(),
  usedAt: timestamp("usedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DiscordVerificationCode = typeof discordVerificationCodes.$inferSelect;
export type InsertDiscordVerificationCode = typeof discordVerificationCodes.$inferInsert;

/**
 * Durable singleton state used by the Heartbeat Minecraft presence monitor.
 * `id = 1` is the only row; player names are stored as a normalized JSON array.
 */
export const minecraftPresenceState = mysqlTable("minecraft_presence_state", {
  id: int("id").primaryKey(),
  scheduleCronTaskUid: varchar("scheduleCronTaskUid", { length: 65 }),
  lastOnline: int("lastOnline").notNull(),
  playerListKnown: int("playerListKnown").notNull(),
  lastPlayerNames: text("lastPlayerNames").notNull(),
  lastCheckedAt: timestamp("lastCheckedAt").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type MinecraftPresenceState = typeof minecraftPresenceState.$inferSelect;
export type InsertMinecraftPresenceState = typeof minecraftPresenceState.$inferInsert;
/**
 * Server registry for the multi-server platform.
 * Secrets are referenced by environment-variable names and never stored in this table.
 */
export const managedServers = mysqlTable("managed_servers", {
  id: int("id").autoincrement().primaryKey(),
  slug: varchar("slug", { length: 64 }).notNull().unique(),
  displayName: varchar("displayName", { length: 128 }).notNull(),
  minecraftHost: varchar("minecraftHost", { length: 255 }).notNull(),
  minecraftPort: int("minecraftPort").default(25565).notNull(),
  discordGuildId: varchar("discordGuildId", { length: 64 }),
  enabled: int("enabled").default(1).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ManagedServer = typeof managedServers.$inferSelect;
export type InsertManagedServer = typeof managedServers.$inferInsert;

/**
 * Non-secret per-server integration mapping. Token/password values remain in env
 * and these fields contain only the environment variable names used by a worker.
 */
export const managedServerConfigs = mysqlTable("managed_server_configs", {
  id: int("id").autoincrement().primaryKey(),
  managedServerId: int("managedServerId").notNull().unique(),
  discordTokenEnv: varchar("discordTokenEnv", { length: 128 }),
  rconHost: varchar("rconHost", { length: 255 }),
  rconPort: int("rconPort").default(25575),
  rconPasswordEnv: varchar("rconPasswordEnv", { length: 128 }),
  channelConfig: text("channelConfig").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ManagedServerConfig = typeof managedServerConfigs.$inferSelect;
export type InsertManagedServerConfig = typeof managedServerConfigs.$inferInsert;

/** Durable administrator-managed Discord Embed templates. */
export const discordEmbedTemplates = mysqlTable("discord_embed_templates", {
  id: int("id").autoincrement().primaryKey(),
  guildId: varchar("guildId", { length: 64 }).notNull(),
  name: varchar("name", { length: 80 }).notNull(),
  title: varchar("title", { length: 256 }).notNull(),
  description: text("description").notNull(),
  color: varchar("color", { length: 16 }).default("EC4899").notNull(),
  imageUrl: varchar("imageUrl", { length: 1024 }),
  footer: varchar("footer", { length: 2048 }),
  defaultChannelId: varchar("defaultChannelId", { length: 64 }),
  createdBy: varchar("createdBy", { length: 64 }).notNull(),
  updatedBy: varchar("updatedBy", { length: 64 }).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type DiscordEmbedTemplate = typeof discordEmbedTemplates.$inferSelect;
export type InsertDiscordEmbedTemplate = typeof discordEmbedTemplates.$inferInsert;

/** Bounded health/audit events for Discord, RCON and economy fulfillment. */
export const healthEvents = mysqlTable("health_events", {
  id: int("id").autoincrement().primaryKey(),
  service: varchar("service", { length: 64 }).notNull(),
  status: mysqlEnum("status", ["ok", "degraded", "down", "error"]).notNull(),
  message: text("message").notNull(),
  metadata: text("metadata").notNull(),
  guildId: varchar("guildId", { length: 64 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type HealthEvent = typeof healthEvents.$inferSelect;
export type InsertHealthEvent = typeof healthEvents.$inferInsert;

/** Player reports submitted from Discord. Cooldown is enforced in application logic. */
export const playerReports = mysqlTable("player_reports", {
  id: int("id").autoincrement().primaryKey(),
  guildId: varchar("guildId", { length: 64 }).notNull(),
  reporterDiscordId: varchar("reporterDiscordId", { length: 64 }).notNull(),
  reporterDisplayName: varchar("reporterDisplayName", { length: 128 }).notNull(),
  targetDiscordId: varchar("targetDiscordId", { length: 64 }),
  targetDiscordName: varchar("targetDiscordName", { length: 128 }).notNull(),
  targetMinecraftIGN: varchar("targetMinecraftIGN", { length: 16 }),
  category: varchar("category", { length: 64 }).notNull(),
  details: text("details").notNull(),
  status: mysqlEnum("status", ["ใหม่", "กำลังตรวจสอบ", "ปิดแล้ว"]).default("ใหม่").notNull(),
  editCount: int("editCount").default(0).notNull(),
  discordMessageId: varchar("discordMessageId", { length: 64 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PlayerReport = typeof playerReports.$inferSelect;
export type InsertPlayerReport = typeof playerReports.$inferInsert;
