export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  discordBotToken: process.env.DISCORD_BOT_TOKEN ?? "",
  discordGuildId: process.env.DISCORD_GUILD_ID ?? "",
  discordStoreChannelId: process.env.DISCORD_STORE_CHANNEL_ID ?? "",
  discordSupportChannelId: process.env.DISCORD_SUPPORT_CHANNEL_ID ?? "",
  discordDonateChannelId: process.env.DISCORD_DONATE_CHANNEL_ID ?? "",
  discordDonateLogChannelId: process.env.DISCORD_DONATE_LOG_CHANNEL_ID ?? "",
  discordOrdersChannelId: process.env.DISCORD_ORDERS_CHANNEL_ID ?? "",
  discordAdminRoleId: process.env.DISCORD_ADMIN_ROLE_ID ?? "",
  discordWelcomeChannelId: process.env.DISCORD_WELCOME_CHANNEL_ID ?? "",
  discordVerificationChannelId: process.env.DISCORD_VERIFICATION_CHANNEL_ID ?? "",
  discordOnlineChannelId: process.env.DISCORD_ONLINE_CHANNEL_ID ?? "",
  discordVerifiedRoleId: process.env.DISCORD_VERIFIED_ROLE_ID ?? "",
  discordMemberRoleId: process.env.DISCORD_MEMBER_ROLE_ID ?? "",
  discordClaimRankGroup: process.env.DISCORD_CLAIM_RANK_GROUP ?? "member",
  publicStoreUrl: process.env.PUBLIC_STORE_URL ?? "",
  rconHost: process.env.RCON_HOST ?? "",
  rconPort: Number(process.env.RCON_PORT ?? 0),
  rconPassword: process.env.RCON_PASSWORD ?? "",
};
